#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rails-dom-testing
Version  : 1.0.6
Release  : 7
URL      : https://rubygems.org/downloads/rails-dom-testing-1.0.6.gem
Source0  : https://rubygems.org/downloads/rails-dom-testing-1.0.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-i18n
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rails-deprecated_sanitizer
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
# Rails::Dom::Testing
[![Build Status](https://travis-ci.org/rails/rails-dom-testing.svg)](https://travis-ci.org/rails/rails-dom-testing)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rails-dom-testing-1.0.6
gem spec %{SOURCE0} -l --ruby > rubygem-rails-dom-testing.gemspec

%build
gem build rubygem-rails-dom-testing.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rails-dom-testing-1.0.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rails-dom-testing-1.0.6  && sed -i "/\.test_order/ s/^/#/" test/test_helper.rb && ruby -Ilib:test -e 'Dir.glob "./test/**/*_test.rb", &method(:require)' && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rails-dom-testing-1.0.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/CountDescripable/cdesc-CountDescripable.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/CountDescripable/pluralize_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/HTMLSelector/cdesc-HTMLSelector.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/assert_dom_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/assert_dom_not_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/cdesc-DomAssertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/compare_doms-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/equal_attribute%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/equal_attribute_nodes%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/equal_children%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/DomAssertions/fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/assert_select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/assert_select_email-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/assert_select_encoded-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/assert_size_match%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/cdesc-SelectorAssertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/css_select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/document_root_element-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/nest_selection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/nodeset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/SelectorAssertions/selecting_no_body%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/_find_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/assert_no_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/assert_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/cdesc-TagAssertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/find_all_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/find_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/TagAssertions/html_scanner_document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/Assertions/cdesc-Assertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/Testing/cdesc-Testing.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/Dom/cdesc-Dom.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/SubstitutionContext/cdesc-SubstitutionContext.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/SubstitutionContext/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/SubstitutionContext/matcher_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/SubstitutionContext/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/SubstitutionContext/substitutable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/SubstitutionContext/substitute%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rails-dom-testing-1.0.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails-dom-testing.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions/dom_assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions/selector_assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions/selector_assertions/count_describable.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions/selector_assertions/html_selector.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions/selector_assertions/substitution_context.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/assertions/tag_assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/lib/rails/dom/testing/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/test/dom_assertions_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/test/selector_assertions_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/test/tag_assertions_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rails-dom-testing-1.0.6/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rails-dom-testing-1.0.6.gemspec
